### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by DreamInvoker** [Cartus/DCGCN#1]
hello, Thanks for your excellent work. I have an issue about datasets. Do you have the preprocessed datasets public available in your paper? It is not easy to preprocess the data (neither AMR nor nmt data) on which to reproduce your work.

**Comment by Cartus** [comment]
Hi @DreamInvoker ,

Thanks for your interest in this work. Unfortunately, the AMR dataset has LDC license, so we are not able to distribute it. For the NMT dataset, we obtained the dataset directly from the author (He gave me the link of the Google Drive). I am not sure if I can release it here.

We will update the Readme section and provide a more detailed data preprocessing tutorial, as it is non-trivial as you mentioned. Also, if the author of the NMT dataset permits (I will ask him), we will release the preprocessed dataset here. 

However, I am kind of busy at this moment (visiting in other countries). I can not guarantee that I can finish all of these in 1 or 2 weeks. Sorry for the inconvenience caused.

**Comment by DreamInvoker** [comment]
@Cartus Thanks for your quickly reply. It's okay that you have your own business and I truly understand you. Looking forward to your data preprocessing tutorial. Have fun and enjoy your visiting!

**Comment by Cartus** [comment]
Hi @DreamInvoker ,

We have update the data preprocessing part and released the preprocessed dataset. Thank you for your attention!

**Comment by DreamInvoker** [comment]
@Cartus Thank you very much, it's a great help for me.
